### PR TITLE
Add torrent stopped

### PR DESCRIPTION
**Pull request by Burmudar**
Add methods to be able to add a torrent in stopped state

### CODE REVIEW

**Comment by mrobinsn** [comment]
@Burmudar Did you mean to close this?

**Comment by Burmudar** [comment]
Hey! Yeah I did. I haven’t tested with the unit tests. Wanted to create a container for that

**Comment by mrobinsn** [comment]
Cool. I just fixed the unit tests on `master`, if you merge master back into this branch Travis CI should run the unit tests automatically against a rutorrent Docker container.

**Comment by Burmudar** [comment]
@mrobinsn Finally got round to fixing the tests!

Added two methods
* AddStopped - adds a torrent by url in stopped state
* AddTorrentStoped - adds a torrent file in stopped state

**Comment by mrobinsn** [comment]
Thanks for the contribution @Burmudar !

This is tagged and released in https://github.com/mrobinsn/go-rtorrent/releases/tag/v1.4.0

**Pull request merged**
